### ISSUE TITLE
SNMP V3 privacy key protocol issue

### ISSUE THREAD

**Issue by RonCuster** [elapouya/python-nagios-helpers#3]
https://github.com/elapouya/python-nagios-helpers/blob/f0adf911fbecae21bcdacabdd9aea2d5458f907b/naghelp/collect.py#L1525

Should be matching against priv_protocol instead of auth_protocol

**Comment by elapouya** [comment]
Thank you for the feedback : I fixed it in v0.2.3 that I just released.
